name: 'Dependency Scan'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: yarn install
      - name: Audit Dependencies for Vulnerabilities
        run: yarn audit
