name: Lighthouse CI

on:
  push:
    branches:
      - master

jobs:
  lighthouse-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build && npm start &
      - name: Run Lighthouse CI
        run: lhci autorun
